### ISSUE TITLE
are there any updates about this project

### ISSUE THREAD

**Issue by nahum-litvin-hs** [hiyainc/jenkins-stateful-agents-demo#2]
hi @jutley  @kiyose,
I just found your blog post and this solution.
and i'm now facing similar challenges. and considering similar alternatives.
have anything changed in your solution? what would you have  done today?

**Comment by jutley** [comment]
We moved off of the pattern described by this blog post. First, we started using the standard k8s plugin for dynamic Jenkins agent pods. We used an EFS volume which could be used across pods, and let each job use a directory within that volume. More recently we scrapped all of our Jenkins work and moved to GitHub Actions. Using a hosted solution has been significantly simpler for us, and has let us focus our time on more important efforts.

**Comment by nahum-litvin-hs** [comment]
thanks alot you gave me a lot to think about.
